package com.ntuc.vendorservice.emailingservice.models;

public enum EmailType {
	ACCOUNT_ACTIVATION,DOCUMENT_SHARE,OTHERS, DOCUMENT_SHARE_PASSWORD, FREE_QUOTA, NEWLY_UPLOADED, ADDED_PARTICIPANT_DOCUMENT_NOTIFICATION, DROP_PARTICIPANT_DOCUMENT_NOTIFICATION, CWF_ACCOUNT_ACTIVATION, VADMIN_ACCOUNT_ACTIVATION, CWF_VADMIN_ACTIVATION
}